name: Build static and push to Repo acm-ucsc/acm-web-2024-deployed

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo acm-ucsc/acm-web-2024
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (static export to ./out)
        run: npm run build

      - name: Push to Repo acm-ucsc/acm-web-2024-deployed
        env:
          TARGET_REPO: acm-ucsc/acm-web-2024-deployed
          TARGET_BRANCH: main
          TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          set -euo pipefail
          : "${TARGET_REPO:?}"; : "${TARGET_BRANCH:?}"; : "${TARGET_REPO_TOKEN:?}"

          WORKDIR=$(mktemp -d)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clone target (may be empty)
          git clone --depth 1 "https://x-access-token:${TARGET_REPO_TOKEN}@github.com/${TARGET_REPO}.git" "$WORKDIR"

          cd "$WORKDIR"

          # If repo is empty (no HEAD/branch), create the target branch
          if ! git rev-parse --verify "$TARGET_BRANCH" >/dev/null 2>&1; then
            # no branch exists yet -> create it
            git checkout -b "$TARGET_BRANCH"
          else
            git checkout "$TARGET_BRANCH"
          fi

          # (Optional) Only wipe if not empty; safe to keep this, but you can remove it.
          find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +

          # Copy export from Repo A
          rsync -a --delete "$GITHUB_WORKSPACE/out/" "$WORKDIR/"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update static export from Repo A (${GITHUB_SHA})"
          git push -u origin "$TARGET_BRANCH"
